name: Main Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Echo Temp Path
        run: echo $RUNNER_TEMP

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with ruff
        run: |
          ruff --format=github --target-version=py311 .

      - name: Test with pytest
        run: |
          pytest
